// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("wavinsentio")
	ScopeName = "github.com/zmoog/otel-collector-contrib/wavinsentio"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
