// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("zcsazzurro")
	ScopeName = "github.com/zmoog/otel-collector-contrib/zcsazzurro"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
